//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2.Modwl
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public Nullable<int> UserID { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
    }
}
